import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from "react-native-responsive-screen";

import { Row } from "native-base";
import { StyleSheet } from "react-native";

const theme = {
  backgrountBlueColor: "#001937",
  skyBlue: "#008eff",
  white: "#fff",
  buttonBlueColor: "#01559e",
  fontBlueColor: "#558cbd",
  boxBackgroundColor: "#002a5a",
  greenColor: "#25b477",
  grayColor: "#20456c",
};

const styles = StyleSheet.create({
  containerStyle: {
    backgroundColor: theme.backgrountBlueColor,
    height: hp(100),
    justifyContent: "center",
  },
  imageStyleSplashScreen: {
    height: hp(15),
    width: wp(80),
    alignSelf: "center",
  },
  homeHeaderStyle: {
    backgroundColor: theme.skyBlue,
    paddingTop: hp(2),
    paddingBottom: hp(3),
  },
  menuStyle: {
    height: hp(6),
    width: wp(8),
    tintColor: theme.white,
    marginLeft: wp(3),
  },
  homeLogoStyle: {
    height: hp(8),
    width: wp(60),
    marginLeft: wp(9),
  },
  inPutContainerStyleHomeHeader: {
    backgroundColor: theme.white,
    width: wp(90),
    alignSelf: "center",
    borderRadius: wp(10),
    flexDirection: "row",
    alignItems: "center",
  },
  searchHeadingStyle: {
    color: theme.white,
    marginLeft: wp(6),
    fontSize: wp(5),
    marginTop: hp(2),
    marginBottom: hp(2),
  },
  searchLogoStyle: {
    height: hp(6),
    width: wp(6),
    marginLeft: wp(3),
  },
  containerStyleForScreens: {
    backgroundColor: theme.backgrountBlueColor,
    flex: 1,
  },
  descriptionTextStyle: {
    marginTop: hp(3),
    marginLeft: wp(5),
    marginRight: wp(5),
    paddingBottom: 2,
    color: theme.white,
    textAlign: "justify",
    marginBottom: hp(3),
  },
  itemImageStyle: {
    height: hp(25),
    resizeMode: "contain",
    width: wp(40),
    alignSelf: "center",
    overflow: "hidden",
    borderRadius: wp(4),
  },
  itemContainerStyle: {
    width: wp(50),
  },
  itemTextStyle: {
    fontSize: wp(8),
    color: theme.white,
    marginLeft: wp(5),
  },
  ItemDescriptionTextStyle: {
    color: theme.white,
    textAlign: "justify",
    marginLeft: wp(5),
  },
  dateStyle: {
    marginTop: hp(2),
    color: theme.white,
    textAlign: "justify",
    marginLeft: wp(5),
  },
  timeStyle: {
    color: theme.skyBlue,
    marginTop: hp(2),
    textAlign: "justify",
  },
  eventVerificationCodeStyle: {
    width: wp(35),
  },
  codeVerificationContainerStyle: {
    flexDirection: "row",
    backgroundColor: "#2a3748",
    width: wp(47),
    alignSelf: "center",
    marginTop: hp(2),
    borderRadius: wp(1),
  },
  headingTextStyle: {
    marginTop: wp(2),
    fontSize: wp(6),
    color: theme.white,
  },
  headingContainerStyle: {
    borderBottomWidth: 1,
    borderBottomColor: theme.skyBlue,
    width: wp(80),
    alignSelf: "center",
    paddingBottom: hp(2),
  },
  drawerContainerStyle: { flex: 1, backgroundColor: "#ae27a7" },
  drawerMenuStyle: {
    resizeMode: "contain",
    height: hp(4),
    width: wp(5),
    tintColor: "white",
  },
  infoIconStyle: {
    resizeMode: "contain",
    height: hp(5),
    width: wp(6),
    tintColor: theme.fontBlueColor,
  },
  socialBtnStyle: {
    resizeMode: "contain",
    height: hp(8),
    width: wp(12),
    marginLeft: wp(1),
    marginRight: wp(1),
  },
  drawerItemContainerStyle: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: wp(5),
    borderTopColor: "#30302d",
    borderTopWidth: 1,
    width: wp(70),
    alignSelf: "center",
    paddingTop: hp(2),
    marginTop: hp(2),
  },
  drawerMenuCloseStyle: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: wp(10),
    borderBottomColor: theme.skyBlue,
    width: wp(60),
    paddingBottom: hp(2),
    marginTop: hp(2),
  },
  drawerMenuNameStyle: {
    color: theme.white,
    fontSize: wp(4),
    marginLeft: wp(5),
  },
  drawerMenuTextStyle: {
    color: theme.white,
    fontSize: wp(3),
    marginLeft: wp(3),
  },
  registerHeadingTextStyle: {
    fontSize: wp(7),
    color: theme.fontBlueColor,
    alignSelf: "center",
    marginTop: hp(5),
  },
  textInputStyle: {
    marginTop: hp(3),
    borderWidth: 0.5,
    alignSelf: "center",
    borderColor: theme.fontBlueColor,
    width: wp(85),
    borderRadius: wp(1),
    color: theme.skyBlue,
  },
  dateCardStyle: {
    flexDirection: "row",
    alignItems: "center",
    width: wp(95),
    justifyContent: "space-between",
    paddingLeft: wp(5),
    paddingRight: wp(5),
    height: hp(8),
  },
  textInputStyleMini: {
    marginTop: hp(3),
    borderWidth: 1,
    borderColor: theme.fontBlueColor,
    width: wp(27),
    borderRadius: wp(1),
    color: theme.skyBlue,
  },
  radioTextStyle: {
    marginLeft: wp(5),
    color: theme.fontBlueColor,
  },
  checkContainerStyle: {
    marginTop: hp(3),
    borderWidth: 1,
    alignSelf: "center",
    borderColor: theme.fontBlueColor,
    width: wp(85),
    borderRadius: wp(1),
    color: theme.skyBlue,
    flexDirection: "row",
    paddingTop: hp(2),
    paddingBottom: hp(2),
  },
  ImagePickerContainerStyle: {
    marginTop: hp(3),
    borderWidth: 1,
    alignSelf: "center",
    borderColor: theme.fontBlueColor,
    width: wp(85),
    borderRadius: wp(1),
    color: theme.skyBlue,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: wp(1),
    paddingRight: wp(1),
    height: hp(8),
  },
  PickerStyle: {
    marginTop: hp(3),
    borderWidth: 1,
    alignSelf: "center",
    borderColor: theme.skyBlue,
    width: wp(80),
    borderRadius: wp(1),
    color: theme.skyBlue,
  },
  checkBoxContainerStyle: {
    marginTop: hp(3),
    alignSelf: "center",
    width: wp(85),
    flexDirection: "row",
  },
  confirmationTextstyle: {
    color: theme.skyBlue,
    fontSize: wp(4),
    marginLeft: wp(5),
  },
  forgetPasswordTextstyle: {
    color: theme.skyBlue,
    fontSize: wp(4),
    marginLeft: wp(8),
    marginTop: hp(2),
  },
  buttonStyle: {
    backgroundColor: theme.buttonBlueColor,
    height: hp(7),
    width: wp(85),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: wp(1),
    marginTop: hp(3),
    marginBottom: hp(6),
  },
  buttonStyleMini: {
    backgroundColor: theme.grayColor,
    height: hp(4),
    width: wp(30),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: wp(1),
    marginTop: hp(1),
    marginBottom: hp(1),
  },
  buttonTextStle: {
    color: theme.white,
    fontSize: wp(4),
  },
  textAreaStyle: {
    borderWidth: 1,
    borderColor: theme.fontBlueColor,
    width: wp(85),
    alignSelf: "center",
    borderRadius: wp(1),
    height: hp(20),
  },
  subMenuStyle: {
    flexDirection: "row",
    alignItems: "center",
  },
  headingStyle: {
    width: wp(75),
    color: theme.skyBlue,
    paddingLeft: wp(2),
    fontSize: wp(4),
  },
  cardStyle: {
    height: hp(13),
    width: wp(20),
    borderWidth: 1,
    backgroundColor: theme.white,
    alignItems: "center",
    marginLeft: wp(1.5),
    marginRight: wp(1.5),
    borderRadius: wp(2),
    marginTop: hp(3),
  },
  cardStyleSelected: {
    height: hp(13),
    width: wp(20),
    borderWidth: 1,
    backgroundColor: theme.greenColor,
    alignItems: "center",
    marginLeft: wp(1.5),
    marginRight: wp(1.5),
    borderRadius: wp(2),
    marginTop: hp(3),
    borderColor: theme.greenColor,
  },
  desTextStyle: {
    color: theme.greenColor,
    marginTop: hp(2),
    width: wp(80),
    textAlign: "center",
    alignSelf: "center",
  },
  textContainerStyle: {
    width: wp(90),
    justifyContent: "space-between",
    alignSelf: "center",
    flexDirection: "row",
  },
  datePickerStyle: {
    flexDirection: "row",
    width: wp(90),
    justifyContent: "space-between",
    alignSelf: "center",
    alignItems: "center",
    borderColor: theme.skyBlue,
    borderRadius: wp(1),
    marginTop: wp(4),
    marginBottom: wp(1),
    paddingLeft: wp(2),
    paddingRight: wp(2),
    backgroundColor: theme.boxBackgroundColor,
  },
  timeContainerStyle: {
    flexDirection: "row",
    width: wp(90),
    justifyContent: "space-between",
    alignSelf: "center",
    alignItems: "center",
    borderColor: theme.skyBlue,
    borderRadius: wp(1),
    marginTop: wp(4),
    marginBottom: wp(1),
  },

  timeBlockStyle: {
    height: hp(15),
    width: wp(35),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    elevation: 1,
    backgroundColor: theme.boxBackgroundColor,
    borderColor: theme.backgrountBlueColor,
    borderRadius: wp(1),
  },
  timeBlockStyleSmall: {
    height: hp(15),
    width: wp(15),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    elevation: 1,
    backgroundColor: theme.boxBackgroundColor,
    borderColor: theme.backgrountBlueColor,
    borderRadius: wp(1),
  },
  timeTextStyle: {
    color: theme.fontBlueColor,
    fontSize: wp(8),
  },
  timeSepratorStyle: {
    fontWeight: "bold",
    fontSize: wp(5),
    color: theme.fontBlueColor,
  },
  miniInputContainerStyle: {
    flexDirection: "row",
    alignSelf: "center",
    width: wp(85),
    justifyContent: "space-between",
  },
  addMoreText: {
    color: theme.greenColor,
    textDecorationLine: "underline",
    alignSelf: "flex-end",
    marginRight: wp(8),
    marginTop: hp(2),
  },
  setp8CardStyle: {
    width: wp(95),
    justifyContent: "space-around",
    padding: wp(4),
  },
  coloredRowStyle: {
    flexDirection: "row",
    backgroundColor: theme.grayColor,
    alignSelf: "center",
    paddingLeft: wp(2),
    paddingRight: wp(2),
    marginTop: hp(2),
    marginBottom: hp(2),
    width: wp(82),
    alignItems: "center",
    borderRadius: wp(1),
  },
  notesTextStyle: {
    width: wp(95),
    alignSelf: "center",
    color: theme.fontBlueColor,
    marginTop: hp(2),
  },
  checkTextStyle: {
    color: theme.fontBlueColor,
    marginLeft: wp(5),
    width: wp(75),
    fontSize: wp(4),
  },
  checkConfirmBoxStyle: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: hp(5),
  },
  buttonsContainerStyle: {
    width: wp(85),
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
  },
  socialButtonStyle: {
    justifyContent: "center",
    flexDirection: "row",
    marginTop: hp(2.5),
    marginBottom: hp(2.5),
  },
  extendedTextStyle: {
    width: wp(95),
    alignSelf: "center",
    marginTop: hp(2),
  },
  roundedImageStyle: {
    height: hp(15),
    width: wp(27),
    overflow: "hidden",
    borderRadius: wp(27) / 2,
    alignSelf: "center",
    marginTop: hp(5),
    marginBottom: hp(3),
    marginBottom: hp(5),
  },
  titleStyle: {
    alignSelf: "center",
    fontSize: wp(5),
    color: theme.fontBlueColor,
  },
  detailContainerStyle: {
    width: wp(85),
    alignSelf: "center",
  },
  tabStyleHomeScreen: {
    height: hp(8),
    backgroundColor: theme.backgrountBlueColor,
    width: wp(50),
  },
  tabTextContainerStyle: {
    justifyContent: "center",
    alignItems: "center",
    height: hp(7.5),
  },
  tabSlideStyle: {
    backgroundColor: theme.skyBlue,
    height: hp(0.5),
  },
  disableTabSlideStyle: {
    height: hp(0.5),
  },
  tabTextStyle: {
    color: theme.skyBlue,
  },
  disableTabTextStyle: {
    color: theme.white,
  },
  useNameStyle: {
    color: theme.white,
    fontSize: wp(9),
    marginLeft: wp(10),
  },
  editTextStyle: {
    color: theme.white,
    fontSize: wp(4),
    color: theme.skyBlue,
    marginLeft: wp(2),
  },
  editTextContainerStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: hp(4),
  },
});
export default styles;
